version: "3"
services:


  the-node-app:
    container_name: node-app-container
    ports:
       - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongo


  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789
  # mongo express app to show the database data act as database client 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456789
      ME_CONFIG_MONGODB_URL: mongodb://root:123456789@mongo:27017/
    depends_on:
      - mongo


  redis:
    image: redis
    depends_on:
      - mongo


  nginx:
    image: nginx:stable-alpine
    ports:
    - "8080:80"



volumes:
  mongodb_volume: