version: "3"
services:
  node-app:
    build: 
        context: .
        target: development
    volumes:
      - ./src:/app/src:ro   
    environment:
      - PORT=4000
      - APP_ENV=development
    command: npm run start-dev  